try {
  console.log(`Caso algo dentro do Try(tente) der algum erro, como exemplo de uma variável não declarada:
  ${fail}`);
} catch (error) {
  console.log(`\n Exibirá o bloco Catch: \n`);
  console.log(error);
}